docker updates

diff --git a/docker/.devcontainer/vscode-open-dev-container b/docker/.devcontainer/vscode-open-dev-container
--- a/docker/.devcontainer/vscode-open-dev-container
+++ b/docker/.devcontainer/vscode-open-dev-container
@@ -7,8 +7,11 @@
 ws_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." &>/dev/null && pwd)"
 
 if ! command -v devcontainer &>/dev/null; then
-    echo "#! Error: 'devcontainer' CLI not found. https://code.visualstudio.com/docs/remote/devcontainer-cli"
-    exit 1
+	echo "#! Error: 'devcontainer' CLI not found. https://code.visualstudio.com/docs/remote/devcontainer-cli"
+	exit 1
 fi
+
+[[ -f "${ws_root}/docker/.env" ]] && touch "${ws_root}/docker/.env"
+[[ -f "${ws_root}/docker/dev.env" ]] && touch "${ws_root}/docker/dev.env"
 
 devcontainer open "${ws_root}/docker"
